services:
  minio:
    image: firstfinger/minio-openmaxio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO S3 API
      - "9001:9001"  # MinIO built-in console
      - "9090:9090"  # OpenMaxIO Console (full-featured UI)
    volumes:
      - ./data:/data
      # Optional: Mount certificates for TLS
      # - ./certs:/data/.minio/certs
    environment:
      # MinIO credentials (CHANGE THESE!)
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ChangeMe123!
      
      # Optional: Custom ports
      # MINIO_API_PORT: 9000
      # MINIO_CONSOLE_PORT: 9001
      # OPENMAXIO_CONSOLE_PORT: 9090
      
      # Optional: Console encryption (recommended for production)
      CONSOLE_PBKDF_PASSPHRASE: your-secret-passphrase-change-me
      CONSOLE_PBKDF_SALT: your-secret-salt-change-me
      
      # Optional: Additional MinIO configuration
      # MINIO_BROWSER: "on"
      # MINIO_REGION_NAME: "us-east-1"
      # MINIO_DOMAIN: "minio.example.com"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - minio

networks:
  minio:
    driver: bridge
