services:
  minio:
    image: firstfinger/minio-openmaxio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9090:9090"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: UL5YXh4vjy3yEAaS4eW8  # Change this to your own username
      MINIO_ROOT_PASSWORD: 36bpUPfiptWp6M7uBFsM75uKbPXZgW  # Change this to your own password
      CONSOLE_PBKDF_PASSPHRASE: dBY2RpcZsDyngFKa  # Change this to your own passphrase
      CONSOLE_PBKDF_SALT: iT2cpVzb8tXPiMr6HJGxJ9otEZo5AVop  # Change this to your own salt
      MINIO_API_PORT: 9000
      MINIO_CONSOLE_PORT: 9001
      OPENMAXIO_CONSOLE_PORT: 9090
    networks:
      - minio
    restart: unless-stopped

networks:
  minio:
    driver: bridge